name: Run unit test

on:
  push:
    branches:
      - main

jobs:
  unit_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f tests/requirements.txt ]; then pip install -r tests/requirements.txt; fi
      - name: Add credentials file
        run: |
          echo "{ \"app_id\": \"${{ secrets.APP_ID }}\", \"app_key\":\"${{ secrets.APP_KEY }}\" }" >> tests/credential.json
      - name: Test with pytest
        run: |
          pytest